### ISSUE TITLE
Using macros as pragmas, which can be imported

### ISSUE THREAD

**Issue by rockcavera** [ZoomTen/pocket-clicker#1]
Your project is very cool.

Looking at your code, I could see that you made this note:
https://github.com/ZoomTen/pocket-clicker/blob/a50922c8b9c6b3d74bf0415437ae759f21e18e14/include/gbPrelude.nim#L1
You can use macros as pragmas. See below:

```nim
import std/macros

macro homeProc*(node: untyped): untyped = # Macros can be marked as exportable
  if node.kind == nnkProcDef:
    addPragma(node,
      newTree(nnkExprColonExpr,
        newIdentNode("codegenDecl"), newLit("$# $#$# NONBANKED")))

  echo "--- AST generated by `homeProc` ---"
  echo astGenRepr(node) # Prints the AST generated by the `homeProc` macro

proc vblank*() {.exportc: "VBlank", homeProc.} =
    ## VBlank interrupt.
    discard

static:
  echo "-----------------------------------"
  echo "---         dumpAstGen          ---"

# Prints the AST of the Nim code below. It can be used to get an idea of how to generate the AST using macros.
dumpAstGen:
  proc vblank*() {.exportc: "VBlank", codegenDecl: "$# $#$# NONBANKED".} =
    ## VBlank interrupt.
    discard
```

**Comment by ZoomTen** [comment]
I read in the manual that macros can be made into pragmas, but at that time I couldn't see how applicable it was here. I think I've got a pretty good idea now (and should git gud in this macro stuff anyway). Thanks for your input!

~~One of the best ways to learn is to be wrong on the Internet. Who knew? xD~~

**Comment by ZoomTen** [comment]
Right, I seem to be running into a problem. The moment I use it, the compiler throws an `Undeclared identifier: vblank` at me when I reference it, and getting rid of the pragma seems to fix it. Any idea why? Or am I just holding it wrong?

**Comment by rockcavera** [comment]
> Right, I seem to be running into a problem. The moment I use it, the compiler throws an `Undeclared identifier: vblank` at me when I reference it, and getting rid of the pragma seems to fix it. Any idea why? Or am I just holding it wrong?

Can you push the code that is giving the problem to a separate branch? So I can look...

Edit: Forgiveness. Forgot to add the result...

```nim
macro homeProc*(node: untyped): untyped =
  result = newStmtList()

  if node.kind == nnkProcDef:
    addPragma(node,
      newTree(nnkExprColonExpr,
        newIdentNode("codegenDecl"), newLit("$# $#$# NONBANKED")))

  add(result, node)
```

**Comment by ZoomTen** [comment]
Ah, there we go. Seems to work like a charm now :)
